[package]
name = "cryo"
version = "0.1.5"
authors = ["yvt <i@yvt.jp>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/yvt/cryo"
description = """
Extend the lifetime of a reference. Safely.
"""
keywords = ["lifetime", "ownership", "reference"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
parking_lot = { version = ">= 0.6, < 0.10", optional = true }
stable_deref_trait = "1.1.1"
